### Instructions:

- You can attempt any number of questions and in any order.  
  See the assignment page for a description of the hurdle requirement for this assessment.
- You may submit your practical for autograding as many times as you like to check on progress, however you will save time by checking and testing your own code before submitting.
- Develop and check your answers in the spaces provided.
- **Replace** the code `raise NotImplementedError()` with your solution to the question.
- Do **NOT** remove any variables other provided markings already provided in the answer spaces.
- Do **NOT** make any changes to this notebook outside of the spaces indicated.  
  (If you do this, the submission system might not accept your work)

### Submitting:

1. Before you turn this problem in, make sure everything runs as expected by resetting this notebook.    
   (You can do this from the menubar above by selecting `Kernel`&#8594;`Restart Kernel and Run All Cells...`)
1. Don't forget to save your notebook after this step.
1. Submit your .ipynb file to Gradescope via file upload or GitHub repository.
1. You can submit as many times as needed.
1. You **must** give your submitted file the **identical** filename to that which you downloaded without changing **any** aspects - spaces, underscores, capitalisation etc. If your operating system has changed the filename because you downloaded the file twice or more you **must** also fix this.  



---

# <mark style="background: #2dc26b; color: #ffffff;" >&nbsp;B3&nbsp;</mark>&ensp;Topic 8: Sorting (ii)

In [ ]:
import numpy as np
from string import ascii_uppercase, ascii_lowercase
from random import shuffle

#### Question 01 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(5 Points)

Write a function defined as:
```python
def lomuto_partition_pivot(arr, low, high):
```
that accepts a list to be sorted and the low and high range of indexes forming the partition to be conisdered for sorting and returns the quicksort pivot value using a Lomuto partition scheme or `None` for a zero length input array. The value of `high` is the actual list index considered.

For example:
```python
lomuto_partition_pivot([10, 9, 5, 2, 6, 4, 7, 1], 0, 7)
```
considers the whole list and returns the value `1` as the pivot value.

In [ ]:
def lomuto_partition_pivot(arr, low, high):
    
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 02 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(5 Points)

Write a function defined as:
```python
def median_of_three_pivot(arr, low, high):
```
that accepts a list to be sorted and the low and high indexes of the partition to be conisdered for sorting and returns the quicksort pivot value using a median partition scheme or `None` for a zero length input array.

For example:
```python
median_of_three_pivot([10, 9, 5, 2, 6, 4, 7], 0, 6)
```
considers the whole list and returns the value `7` being the middle value in `10`, `2` and `7`.

In [ ]:
def median_of_three_pivot(arr, low, high):
    
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 03 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def median_quicksort(arr, reverse = False):
```
that uses a quicksort with median partition scheme to sort a list of floats in-place. The parameter `reverse` selects the direction of the sort order where `reverse == True` indicates a descending sort.

In [ ]:
def median_quicksort(arr, reverse = False):
    
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 04 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
    def quicksort_numpy_arrays (alist, reverse = False):
```
that performs an ascending, inplace quicksort with a partition scheme of your choice on a list of NumPy arrays (`alist`) based on the sum of values in the array. The parameter `reverse` selects the direction of the sort order where `reverse == True` indicates a descending sort.

For example, give an input list of arrays like:
```python
[array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([0]),
 array([0, 1, 2]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4])]
```
the function will sort alist in place like:
```python
[array([0]),
 array([0, 1, 2]),
 array([0, 1, 2, 3, 4]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8])]
```

In [ ]:
def quicksort_numpy_arrays (alist, reverse = False):
    
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 05 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def quicksort_alphabetical (arr, ignorecase = False):
 ```
that sorts a list of characters (single letter strings) in-place according to alphabetical order. When `ignorecase == True`, the case of letters in the list should be ignored.  When `ignorecase == False`, the sort should respect the case of the list according to Python's default behaviour: uppercase characters sort in preference to lowercase characters. 

In [ ]:
def quicksort_alphabetical (arr, ignorecase = False):
    
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 06 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```Python
def insertion_sort_string (un_list):
```
that sorts a list of strings in-place in descending order of their length using an insertion sort.

In [ ]:
def insertion_sort_string (un_list):
    
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 07 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def insertion_sort_dict_by_key (un_dict):
```
that performs an insertion sort that sorts a dict by ascending values in-place while retaining identical keys.

For example, given a dictionary:
```python
d = {
    1: 101,
    2: 2,
    8: -1,
}
```
would be sorted as:
```python
d = {
    1: -1,
    2: 2,
    8: 101,
}
```

In [ ]:
def insertion_sort_dict_by_key (un_dict):
    
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 08 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def recursive_insertion_sort (arr, index, reverse):
```
that performs a recursive insertion sort in-place on a list of floats taking a `reverse` parameter to signal whether the floats are to be in ascending on descending order.

In [ ]:
def recursive_insertion_sort (arr, index, reverse = False):
    
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 09 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def median_alpha_pivot(str_list, low, high):
```
that accepts a list of capitalised names, the index of the start and end of the partition in the list and returns a 'median of three' pivot value using a median partition scheme or `None` for a zero length input array. 

In calculating the pivot, the first letter of each string is given a weighting according to its index in `list(string.ascii_uppercase)` and the value returned is that index. 

Thus, in a list like:
```python
["Majid", "Victoria", "Tashreque", "Xiefeng", "Fu", "Biao", "Rui"]
```
in calculating the pivot for the whole of the list, we consider the values:
- 12 (the index of 'M' in string.ascii_uppercase), 
- 23 (the index of 'X' in string.ascii_uppercase), and 
- 17 (the index of 'R' in string.ascii_uppercase)   
returning `17` as our first pivot value.


In [ ]:
def median_alpha_pivot(str_list, low, high):
    
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 10 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def median_quicksort_by_first_letter (str_list):
```   

that implements a **recursive** quicksort that sorts a list of capitalised names according to their first letter using the median partition scheme per the details expressed in Question 09. 

Thus, given a list like:
```python
["Majid", "Victoria", "Tashreque", "Xiefeng", "Fu", "Biao", "Rui"]
```
when sorted in-place, the list is:
```python
['Fu', 'Rui', 'Biao', 'Majid', 'Xiefeng', 'Victoria', 'Tashreque']
```

In [ ]:
def median_quicksort_by_first_letter (str_list):

    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 11 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def insertion_sort_by_tuple_sum (ulist, reverse = False):
```
that sorts a list of numerical tuples in-place by the sum of all values in the tuple. The parameter `reverse` indicates an ascending or descending sort. 

In [ ]:
def insertion_sort_by_tuple_sum (ulist, reverse = False):
     
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
# Testing Cell (Do NOT modify this cell)