### Instructions:

- You can attempt any number of questions and in any order.  
  See the assignment page for a description of the hurdle requirement for this assessment.
- You may submit your practical for autograding as many times as you like to check on progress, however you will save time by checking and testing your own code before submitting.
- Develop and check your answers in the spaces provided.
- **Replace** the code `raise NotImplementedError()` with your solution to the question.
- Do **NOT** remove any variables other provided markings already provided in the answer spaces.
- Do **NOT** make any changes to this notebook outside of the spaces indicated.  
  (If you do this, the submission system might not accept your work)

### Submitting:

1. Before you turn this problem in, make sure everything runs as expected by resetting this notebook.    
   (You can do this from the menubar above by selecting `Kernel`&#8594;`Restart Kernel and Run All Cells...`)
1. Don't forget to save your notebook after this step.
1. Submit your .ipynb file to Gradescope via file upload or GitHub repository.
1. You can submit as many times as needed.
1. You **must** give your submitted file the **identical** filename to that which you downloaded without changing **any** aspects - spaces, underscores, capitalisation etc. If your operating system has changed the filename because you downloaded the file twice or more you **must** also fix this.  



---

# <mark style="background: #2dc26b; color: #ffffff;" >&nbsp;B3&nbsp;</mark>&ensp;Topic 8: Sorting (ii)

In [73]:
import numpy as np
from string import ascii_uppercase, ascii_lowercase
from random import shuffle

#### Question 01 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(5 Points)

Write a function defined as:
```python
def lomuto_partition_pivot(arr, low, high):
```
that accepts a list to be sorted and the low and high range of indexes forming the partition to be conisdered for sorting and returns the quicksort pivot value using a Lomuto partition scheme or `None` for a zero length input array. The value of `high` is the actual list index considered.

For example:
```python
lomuto_partition_pivot([10, 9, 5, 2, 6, 4, 7, 1], 0, 7)
```
considers the whole list and returns the value `1` as the pivot value.

In [74]:
def lomuto_partition_pivot(arr, low, high):
    
    # YOUR CODE HERE
    if len(arr) == 0 or low >= high:
        return None
    
    pivot = arr[high]
    i = low - 1
    
    for j in range(low, high):
        if arr[j] <= pivot:
            i += 1
            
            arr[i], arr[j] = arr[j], arr[i]
            
    arr[i + 1], arr[high] = arr[high], arr[i + 1]
    return arr[i + 1]
lomuto_partition_pivot([10, 9, 5, 2, 6, 4, 7, 1], 0, 7)


1

In [75]:
# Testing Cell (Do NOT modify this cell)

#### Question 02 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(5 Points)

Write a function defined as:
```python
def median_of_three_pivot(arr, low, high):
```
that accepts a list to be sorted and the low and high indexes of the partition to be conisdered for sorting and returns the quicksort pivot value using a median partition scheme or `None` for a zero length input array.

For example:
```python
median_of_three_pivot([10, 9, 5, 2, 6, 4, 7], 0, 6)
```
considers the whole list and returns the value `7` being the middle value in `10`, `2` and `7`.

In [76]:
def median_of_three_pivot(arr, low, high):
    
    # YOUR CODE HERE
    if len(arr) == 0 or low >= high:
        return None
    
    mid = (low + high) // 2
    
    if arr[low] <= arr[mid] <= arr[high] or arr[high] <= arr[mid] <= arr[low]:
        return arr[mid]
    
    elif arr[mid] <= arr[low] <= arr[high] or arr[high] <= arr[low] <= arr[mid]:
        return arr[low]
    
    else:
        return arr[high]
    
median_of_three_pivot([10, 9, 5, 2, 6, 4, 7], 0, 6)

7

In [77]:
# Testing Cell (Do NOT modify this cell)

#### Question 03 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def median_quicksort(arr, reverse = False):
```
that uses a quicksort with median partition scheme to sort a list of floats in-place. The parameter `reverse` selects the direction of the sort order where `reverse == True` indicates a descending sort.

In [184]:
def median_quicksort(arr, reverse = False):
    if len(arr) == 0:
            return 
    
    # YOUR CODE HERE
    
    def quicksort(lst, first=0, last=None):
        if last is None:
            last = len(lst) - 1
        
        if first >= last:
            return
        
        pivot = median_of_three_pivot(lst, first, last)
        i, j = first, last
        while i <= j:
            if not reverse:
                while lst[i] < pivot:
                    i += 1
                while lst[j] > pivot:
                    j -= 1
            
            else:
                while lst[i] > pivot:
                    i += 1
                while lst[j] < pivot:
                    j -= 1
                    
            if i <= j:
                lst[i], lst[j] = lst[j], lst[i]
                i += 1
                j -= 1
                
        quicksort(lst, first, j)
        quicksort(lst, i, last)
        
        return lst
    return quicksort(arr)
median_quicksort([10, 9, 5, 2, 6, 4, 7], reverse=True)

[10, 9, 7, 6, 5, 4, 2]

In [79]:
# Testing Cell (Do NOT modify this cell)

#### Question 04 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
    def quicksort_numpy_arrays (alist, reverse = False):
```
that performs an ascending, inplace quicksort with a partition scheme of your choice on a list of NumPy arrays (`alist`) based on the sum of values in the array. The parameter `reverse` selects the direction of the sort order where `reverse == True` indicates a descending sort.

For example, give an input list of arrays like:
```python
[array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([0]),
 array([0, 1, 2]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4])]
```
the function will sort alist in place like:
```python
[array([0]),
 array([0, 1, 2]),
 array([0, 1, 2, 3, 4]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8])]
```

In [80]:
def quicksort_numpy_arrays (alist, reverse = False):
    
    # YOUR CODE HERE
    def quicksort(arr, first=0, last=None):
        if last == None:
            last = len(arr) - 1
            
        if first >= last:
            return arr
        
        i, j = first, last
        pivot = arr[first]
        
        while i <= j:
            if not reverse:
                while np.sum(arr[i]) < np.sum(pivot):
                    i += 1
                while np.sum(arr[j]) > np.sum(pivot):
                    j -= 1
            else:
                while np.sum(arr[i]) > np.sum(pivot):
                    i += 1
                while np.sum(arr[j]) < np.sum(pivot):
                    j -= 1
                
            if  i <= j:
                arr[i], arr[j] = arr[j], arr[i]
                i += 1
                j -= 1
        
        quicksort(arr, first, j)
        quicksort(arr, i, last)

        return arr

    return quicksort(alist)

In [81]:
alist = [np.array(np.arange(9)),
         np.array([0]),
         np.array([0, 1, 25]),
         np.array(np.arange(7)), 
         np.array(np.arange(5))]

quicksort_numpy_arrays(alist)

[array([0]),
 array([0, 1, 2, 3, 4]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([ 0,  1, 25]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8])]

In [82]:
# Testing Cell (Do NOT modify this cell)

#### Question 05 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def quicksort_alphabetical (arr, ignorecase = False):
 ```
that sorts a list of characters (single letter strings) in-place according to alphabetical order. When `ignorecase == True`, the case of letters in the list should be ignored.  When `ignorecase == False`, the sort should respect the case of the list according to Python's default behaviour: uppercase characters sort in preference to lowercase characters. 

In [83]:
def quicksort_alphabetical (arr, ignorecase = False):
    
    # YOUR CODE HERE
    def quicksort(arr,first=0, last=None):
        if last is None:
            last = len(arr) - 1
            
        if first >= last:
            return arr
        
        i, j = first, last
        pivot = arr[first]
        
        while i <= j:
            if ignorecase:
                while arr[i].lower() < pivot.lower():
                    i += 1
                while arr[j].lower() > pivot.lower():
                    j -= 1
                    
            else:
                while arr[i] < pivot:
                    i += 1
                while arr[j] > pivot:
                    j -= 1
                    
            if i <= j:
                arr[i], arr[j] = arr[j], arr[i]
                i += 1
                j -= 1
                    
        quicksort(arr, first, j)
        quicksort(arr, i, last)
        
        return arr
    
    return quicksort(arr)



In [84]:
# Testing Cell (Do NOT modify this cell)

#### Question 06 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```Python
def insertion_sort_string (un_list):
```
that sorts a list of strings in-place in descending order of their length using an insertion sort.

In [185]:
def insertion_sort_string (un_list):
    
    # YOUR CODE HERE
    for i, v in enumerate(un_list):
        j = i - 1
        
        while j >= 0 and len(un_list[j]) < len(v):
            un_list[j + 1] = un_list[j]
            j -= 1
            
        un_list[j + 1] = v
    
    return un_list

insertion_sort_string(["Majid", "Victoria", "Tashreque", "Xiefeng", "Fu", "Biao", "Rui"])

['Tashreque', 'Victoria', 'Xiefeng', 'Majid', 'Biao', 'Rui', 'Fu']

In [86]:
# Testing Cell (Do NOT modify this cell)

#### Question 07 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def insertion_sort_dict_by_key (un_dict):
```
that performs an insertion sort that sorts a dict by ascending values in-place while retaining identical keys.

For example, given a dictionary:
```python
d = {
    1: 101,
    2: 2,
    8: -1,
}
```
would be sorted as:
```python
d = {
    1: -1,
    2: 2,
    8: 101,
}
```

In [195]:
def insertion_sort_dict_by_key(un_dict):
    # 获取字典的所有键
    keys = list(un_dict.keys())

    # 遍历每个键，从第二个键开始
    for i in range(1, len(keys)):
        current_key = keys[i]          # 当前键
        current_value = un_dict[current_key]  # 当前值
        j = i - 1
        
        # 在已经排序的部分找到合适的位置
        while j >= 0 and un_dict[keys[j]] > current_value:
            keys[j + 1] = keys[j]  # 移动较大的键
            j -= 1
        
        # 将当前键放到合适的位置
        keys[j + 1] = current_key
    
    # 根据排序后的键构建新的字典
    sorted_dict = {key: un_dict[key] for key in keys}
    
    # 将原字典替换为排序后的字典
    un_dict.clear()  # 清空原字典
    un_dict.update(sorted_dict)  # 更新原字典

    return un_dict

# 示例字典
d = {
    1: 101,
    2: 2,
    8: -1,
}

# 对字典按值进行排序
sorted_dict = insertion_sort_dict_by_key(d)
print(sorted_dict)


{8: -1, 2: 2, 1: 101}


In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 08 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def recursive_insertion_sort (arr, index, reverse):
```
that performs a recursive insertion sort in-place on a list of floats taking a `reverse` parameter to signal whether the floats are to be in ascending on descending order.

In [191]:
def recursive_insertion_sort (arr, index, reverse = False):
    
    # YOUR CODE HERE
    if index <= 0:
        return arr
    
    recursive_insertion_sort(arr, index - 1, reverse)
    key = arr[index]
    j = index - 1
    
    if not reverse:
        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j -= 1
            
    else:
        while j >= 0 and arr[j] < key:
            arr[j + 1] = arr[j]
            j -= 1
    
    arr[j + 1] = key

    return arr
    
lst = [1]
recursive_insertion_sort(lst, len(lst) - 1, reverse=True)


[1]

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 09 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def median_alpha_pivot(str_list, low, high):
```
that accepts a list of capitalised names, the index of the start and end of the partition in the list and returns a 'median of three' pivot value using a median partition scheme or `None` for a zero length input array. 

In calculating the pivot, the first letter of each string is given a weighting according to its index in `list(string.ascii_uppercase)` and the value returned is that index. 

Thus, in a list like:
```python
["Majid", "Victoria", "Tashreque", "Xiefeng", "Fu", "Biao", "Rui"]
```
in calculating the pivot for the whole of the list, we consider the values:
- 12 (the index of 'M' in string.ascii_uppercase), 
- 23 (the index of 'X' in string.ascii_uppercase), and 
- 17 (the index of 'R' in string.ascii_uppercase)   
returning `17` as our first pivot value.


In [160]:
def median_alpha_pivot(str_list, low, high):
    
    # YOUR CODE HERE
    index = {}
    for i, v in enumerate(list(ascii_uppercase)):
        index[v] = i
    
    if low >= high:
        return
    
    mid = (low + high) // 2
    pivot_lst = sorted([index[str_list[low][0]], index[str_list[mid][0]], index[str_list[high][0]]])
    
    return pivot_lst[1]

lst = ["Majid", "Victoria", "Tashreque", "Xiefeng", "Fu", "Biao", "Rui"]
median_alpha_pivot(lst, 0, len(lst) - 1)

17

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 10 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def median_quicksort_by_first_letter (str_list):
```   

that implements a **recursive** quicksort that sorts a list of capitalised names according to their first letter using the median partition scheme per the details expressed in Question 09. 

Thus, given a list like:
```python
["Majid", "Victoria", "Tashreque", "Xiefeng", "Fu", "Biao", "Rui"]
```
when sorted in-place, the list is:
```python
['Fu', 'Rui', 'Biao', 'Majid', 'Xiefeng', 'Victoria', 'Tashreque']
```

In [169]:
def median_alpha_pivot(str_list, low, high):
    
    # YOUR CODE HERE
    index = {}
    for i, v in enumerate(list(ascii_uppercase)):
        index[v] = i
    
    if low >= high:
        return
    
    mid = (low + high) // 2
    pivot_lst = sorted([index[str_list[low][0]], index[str_list[mid][0]], index[str_list[high][0]]])
    
    return pivot_lst[1]

def median_quicksort_by_first_letter (str_list):

    # YOUR CODE HERE
    index = {letter: i for i, letter in enumerate(ascii_uppercase)}
    
    def recursive(lst, first=0, last=None):
        if last is None:
            last =  len(lst) - 1
        
        if first >= last:
            return lst
        
        i, j = first, last
        pivot = median_alpha_pivot(lst, first, last)
        
        while i <= j:
            while index[lst[i][0]] < pivot:
                i += 1
                
            while index[lst[j][0]] > pivot:
                j -= 1
                
            if i <= j:
                lst[i], lst[j] = lst[j], lst[i]
                i += 1
                j -= 1
        
        recursive(lst, first, j)
        recursive(lst, i, last)
        
        return lst

    return recursive(str_list)

str_list = ["Majid", "Victoria", "Tashreque", "Xiefeng", "Fu", "Biao", "Rui"]
median_quicksort_by_first_letter(str_list)

['Biao', 'Fu', 'Majid', 'Rui', 'Tashreque', 'Victoria', 'Xiefeng']

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 11 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def insertion_sort_by_tuple_sum (ulist, reverse = False):
```
that sorts a list of numerical tuples in-place by the sum of all values in the tuple. The parameter `reverse` indicates an ascending or descending sort. 

In [176]:
def insertion_sort_by_tuple_sum (ulist, reverse = False):
     
    # YOUR CODE HERE
    for i, v in enumerate(ulist):
        j = i - 1
        key = sum(v)
        
        if not reverse:
            while j >= 0 and sum(ulist[j]) > key:
                ulist[j + 1] = ulist[j]
                j -= 1
        else:
            while j >= 0 and sum(ulist[j]) < key:
                ulist[j + 1] = ulist[j]
                j -= 1
                
        ulist[j + 1] = v
        
    return ulist

lst = [(1, 2, 3), (6, 7, 8, 9),(4, 5)]
insertion_sort_by_tuple_sum(lst, reverse=True)

[(6, 7, 8, 9), (4, 5), (1, 2, 3)]

In [ ]:
# Testing Cell (Do NOT modify this cell)