### Instructions:

- You can attempt any number of questions and in any order.  
  See the assignment page for a description of the hurdle requirement for this assessment.
- You may submit your practical for autograding as many times as you like to check on progress, however you will save time by checking and testing your own code before submitting.
- Develop and check your answers in the spaces provided.
- **Replace** the code `raise NotImplementedError()` with your solution to the question.
- Do **NOT** remove any variables other provided markings already provided in the answer spaces.
- Do **NOT** make any changes to this notebook outside of the spaces indicated.  
  (If you do this, the submission system might not accept your work)

### Submitting:

1. Before you turn this problem in, make sure everything runs as expected by resetting this notebook.    
   (You can do this from the menubar above by selecting `Kernel`&#8594;`Restart Kernel and Run All Cells...`)
1. Don't forget to save your notebook after this step.
1. Submit your .ipynb file to Gradescope via file upload or GitHub repository.
1. You can submit as many times as needed.
1. You **must** give your submitted file the **identical** filename to that which you downloaded without changing **any** aspects - spaces, underscores, capitalisation etc. If your operating system has changed the filename because you downloaded the file twice or more you **must** also fix this.  



---

# <mark style="background: #2dc26b; color: #ffffff;" >&nbsp;B3&nbsp;</mark>&nbsp;Topic 8: Practice Sorting (i)

#### Question 01 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
    def sort_np.np.arrays_by_value (alist):
```
that performs an ascending, inplace bubble sort on a list of NumPy np.arrays `alist` based on the **sum of values** in each np.array. 

For example, give an input list of np.arrays like:
```python
[np.array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 np.array([0]),
 np.array([0, 1, 25]),
 np.array([0, 1, 2, 3, 4, 5, 6]),
 np.array([0, 1, 2, 3, 4])]
```
the function will sort `alist` in place like:
```python
[np.array([0]),
 np.array([0, 1, 2, 3, 4]),
 np.array([0, 1, 2, 3, 4, 5, 6]),
 np.array([0, 1, 25]),
 np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])]
```

In [2]:
import numpy as np

def sort_arrays_by_value (alist):
    # Write your solution here
    ...
    # YOUR CODE HERE
    for j in range(len(alist) - 1):
        for i in range(len(alist) - 1):
            if np.sum(alist[i]) > np.sum(alist[i + 1]):
                alist[i], alist[i + 1] = alist[i + 1], alist[i]
            

    return alist

alist = [np.array(np.arange(9)),
         np.array([0]),
         np.array([0, 1, 25]),
         np.array(np.arange(7)), 
         np.array(np.arange(5))]
sort_arrays_by_value(alist)

[array([0]),
 array([0, 1, 2, 3, 4]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([ 0,  1, 25]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8])]

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 02 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def selection_sort_n (un_list, n):
```
that uses **selection sort** to sort a list in-place ascending from `un_list[0]` and performs **exactly** ‘n’ swaps. i.e.: the function terminates when ‘n’ swaps have been performed and returns `None`. 

For example:
```python
my_list = [27, 12, 23, 1, 19, 14]
selection_sort_n (my_list, 1)
assert my_list == [14, 12, 23, 1, 19, 27]
```

---
<details>
  <summary><span style="color:blue">Sorting in-place and return values</span></summary>
  When a sort is performed in-place, the list (or variable) passed into the function is used to conduct the sort (rather than creating a new list of data which would add time and space complexity). Because of this, the function does not need to return the sorted list - since the caller of the list created it and retains access to it once sorted.
    Every Python function returns a value once it completes unless it raises an exception. If there is no explicit return statement in the function, it returns the value None. In this question, therefore, there is no need to include a return statement. In fact, returning any value (except None implicitly) will be an error.
</details>

In [55]:
def selection_sort_n (un_list, n):
    # Write your solution here
    ...
    # YOUR CODE HERE
    last_index = len(un_list) - 1
    step = last_index - n
    
    for curr in range(last_index, step, -1):
        max_index = 0
        for  location in range(1, curr + 1):
            if un_list[location] > un_list[max_index]:
                max_index = location
                
        un_list[curr], un_list[max_index] = un_list[max_index], un_list[curr]

    return un_list
    

[1, 12, 14, 19, 23, 27]

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 03 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def bubble_sort_n (un_list, n):
```
that applies an in-place **bubble sort** for exactly 'n' iterations. i.e.: the function terminates (returns) after the n'th iteration of the sort.

For example:
```python
bubble_sort_n ([27, 13, 23, 1, 12, 14], 2) == [13, 1, 12, 14, 23, 27]
```

In [49]:
def bubble_sort_n (un_list, n):
    # Write your solution here
    ...
    # YOUR CODE HERE
    for i in range(0, n):
        for j in range(0, len(un_list)- i - 1):
            if un_list[j] > un_list[j + 1]:
                un_list[j], un_list[j + 1] = un_list[j + 1], un_list[j]
    
    return un_list

bubble_sort_n ([27, 13, 23, 1, 12, 14], 12)

[1, 12, 13, 14, 23, 27]

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 04 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def sort_dict_by_value (un_dict):
```
that performs a sort of any type that sorts the ascending values of a dictionary in-place while retaining identical keys.

For example, given a dictionary:
```python
d = {
    1: 101,
    2: 2,
    8: -1,
}
```
would be sorted as:
```python
d = {
    1: -1,
    2: 2,
    8: 101,
}
```

In [52]:
def sort_dict_by_value (un_dict):
    # Write your solution here
    ...
    # YOUR CODE HERE
    list_ = [list(item) for item in un_dict.items()]
    for curr in range(len(list_) - 1, 0, -1):
        max_idx = 0
        for location in range(1, curr + 1):
            if list_[location][1] > list_[max_idx][1]:
                max_idx = location
                
        list_[curr][1], list_[max_idx][1] = list_[max_idx][1], list_[curr][1]
    
    result = dict(list_)
    return result

In [ ]:
d = {1: 101, 2: 2, 8: -1, 3: 3}
sort_dict_by_value(d)

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 05 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def recursive_selection_sort_by_string_length (str_list):
```   

that implements a **recursive** selection_sort that sorts a list of capitalised names by length. 

Thus, in a list like:
```python
["Majid", "Victoria", "Tashreque", "Xiefeng", "Fu", "Biao", "Rui"]
```
when sorted in-place, the `str_list` is:
```python
['Fu', 'Rui', 'Biao', 'Majid', 'Xiefeng', 'Victoria', 'Tashreque']
```

In [21]:
def recursive_selection_sort_by_string_length (str_list):
    # Write your solution here
    ...
    # YOUR CODE HERE
    def recursive_selection_sort(lst, n=None):
        if n == None:
            n = len(lst)
        
        if n <= 1:
            return lst
        
        max_idx = 0
        for i in range(1, n):
            if len(lst[i]) > len(lst[max_idx]):
                max_idx = i
                
        lst[max_idx], lst[n - 1] = lst[n - 1], lst[max_idx]
            
        return recursive_selection_sort(lst, n - 1)
    
    return recursive_selection_sort(str_list)

str_list = ["Majid", "Victoria", "Tashreque", "Xiefeng", "Fu", "Biao", "Rui"]
recursive_selection_sort_by_string_length(str_list)

['Fu', 'Rui', 'Biao', 'Majid', 'Xiefeng', 'Victoria', 'Tashreque']

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 06 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def iterative_selection_sort_by_string_length (str_list):
```   

that implements an **iterative** selection_sort identical in requirements to Question 05. 

In [56]:
def iterative_selection_sort_by_string_length (str_list):
    # Write your solution here
    ...
    # YOUR CODE HERE
    for curr in range(len(str_list) - 1, 0, -1):
        max_idx = 0
        
        for i in range(1, curr + 1):
            if len(str_list[i]) > len(str_list[max_idx]):
                max_idx = i
        
        str_list[max_idx], str_list[curr] = str_list[curr], str_list[max_idx]
    
    return str_list

In [57]:

str_list = ["Majid", "Victoria", "Tashreque", "Xiefeng", "Fu", "Biao", "Rui"]
iterative_selection_sort_by_string_length(str_list)
# assert recursive_selection_sort_by_string_length(str_list) == iterative_selection_sort_by_string_length(str_list)

['Fu', 'Rui', 'Biao', 'Majid', 'Xiefeng', 'Victoria', 'Tashreque']

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 07 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Using the function definition:
```python
    def selection_sort_to_dest (source, destination = []):
```
write a recursive implementation of a selection sort that accepts a list of unsorted ints called `source` and sorts these values into a list called `destination` in descending order of value. 

For example, given a source list like:
```python
[3, 6, 1, -1, 99]
```
the function should remove the largest element from source and add it to the destination as follows:
```python
source            destination 
[3, 6, 1, -1, 99] []
[3, 6, 1, -1]     [99]
[3, 1, -1]        [99, 6]
[1, -1]           [99, 6, 3]
[-1]              [99, 6, 3, 1]
[]                [99, 6, 3, 1, -1]
```

In [62]:
def selection_sort_to_dest (source, destination = []):
    # Write your solution here
    ...
    # YOUR CODE HERE
    def recursive(lst: list, n=None):
        if n == None:
            n = len(lst)
        
        if n == 0:
            return 
        
        max_idx = 0
        for i in range(1, n):
            if lst[i] > lst[max_idx]:
                max_idx = i
        
        destination.append(lst[max_idx])
        lst.pop(max_idx)
        
        return recursive(lst, n - 1)
    
    recursive(source)
    return destination

selection_sort_to_dest([3, 6, 1, -1, 99])

[99, 6, 3, 1, -1]

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 08 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as: 
```python
def sort_floats_to_list (source):
```
that performs a sort of any type on a source list of unsorted floats and returns a destination list that will contain the sorted data in ascending order. An in place sort may not be used and the source list must remain unchanged.

For example:
```python
in_list = [19.8, 1.1, 16.9, 0.1, -7.6]
out_list = sort_floats_to_list (in_list)
```
returns:
```python
[-7.6, 0.1, 1.1, 16.9, 19.8]
```
while the source in_list is unchanged.

In [67]:
def sort_floats_to_list (source):
    # Write your solution here
    ...
    # YOUR CODE HERE
    destination = source.copy()
    
    for curr in range(len(source) - 1, 0, -1):
        max_idx = 0
        
        for i in range(1, curr + 1):
            if destination[i] > destination[max_idx]:
                max_idx = i
        
        destination[curr], destination[max_idx] = destination[max_idx], destination[curr]
        
    return destination

sort_floats_to_list ([19.8, 1.1, 16.9, 0.1, -7.6])

[-7.6, 0.1, 1.1, 16.9, 19.8]

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 09 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Writing a recursive bubble sort is more difficult than an iterative approach. However, if we consider the bubble sort algorithm, after one pass of the sort, we have fixed one value in place: the last element of our input. For example if we consider a first pass over a list of ints, we are certain that the last value of the list is now in place.
```python
[5, 1, 4, 2, 8] –> [1, 5, 4, 2, 8] 
[1, 5, 4, 2, 8] –> [1, 4, 5, 2, 8] 
[1, 4, 5, 2, 8] –> [1, 4, 2, 5, 8] 
[1, 4, 2, 5, 8] –> [1, 4, 2, 5, 8]
```
Hence, we could now recurse over the unsorted portion of the list excluding the last element. We also have two terminating conditions:
- a pass has made no swaps, or
- we have done sufficient swaps to guarantee that all the data is now sorted.

Write a function defined as:
```python
    def recursive_bubble_sort (intlist):
```
that completes an inplace, **recursive** bubble sort of an input list.

In [37]:
def recursive_bubble_sort (intlist):
    # Write your solution here
    ...
    # YOUR CODE HERE
    def recursive(lst, n=None):
        if n == None:
            n = len(lst)
            
        if n <= 1:
            return lst
        
        for i in range(n - 1):
            if lst[i] > lst[i + 1]:
                lst[i], lst[i + 1] = lst[i + 1], lst[i]
                
        return recursive(lst, n -1)
        
    return recursive(intlist)

recursive_bubble_sort([5, 1, 4, 2, 8])

[1, 2, 4, 5, 8]

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 10 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def sinking_sort_list_by_value (un_list):
```
that performs a **bubble sort** to sort a list by **descending value** (aka: *sinking sort*) and returns a list of ```(original_location, value)``` tuples with the 1st item reflecting the original position of the value in the list and the second item being the value itself.

For example, a list like:
```python
[6, 2, 1, 5, 4]
```
is sorted like:
```python
[6, 5, 4, 2, 1]
```
and the function constructs a list of tuples mapping the values to their original positions and returns:
```python
[(0, 6), (3, 5), (4, 4), (1, 2), (2, 1)]
```
i.e.: a list of ```(i, v)``` tuples sorted in descending order of ```v```, where ```i``` is the index in the original list. 

In [28]:
def sinking_sort_list_by_value (un_list):
    # Write your solution here
    ...
    # YOUR CODE HERE
    destination = list(zip(range(len(un_list)), un_list))
    
    for i in range(0, len(destination) - 1):
        for j in range(0, len(destination) - 1 - i):
            if destination[j][1] <  destination[j + 1][1]:
                destination[j], destination[j + 1] = destination[j + 1], destination[j]
                
    return destination
sinking_sort_list_by_value([6, 2, 1, 5, 4])

[(0, 6), (3, 5), (4, 4), (1, 2), (2, 1)]

In [ ]:
# Testing Cell (Do NOT modify this cell)