### Instructions:

- You can attempt any number of questions and in any order.  
  See the assignment page for a description of the hurdle requirement for this assessment.
- You may submit your practical for autograding as many times as you like to check on progress, however you will save time by checking and testing your own code before submitting.
- Develop and check your answers in the spaces provided.
- **Replace** the code `raise NotImplementedError()` with your solution to the question.
- Do **NOT** remove any variables other provided markings already provided in the answer spaces.
- Do **NOT** make any changes to this notebook outside of the spaces indicated.  
  (If you do this, the submission system might not accept your work)

### Submitting:

1. Before you turn this problem in, make sure everything runs as expected by resetting this notebook.    
   (You can do this from the menubar above by selecting `Kernel`&#8594;`Restart Kernel and Run All Cells...`)
1. Don't forget to save your notebook after this step.
1. Submit your .ipynb file to Gradescope via file upload or GitHub repository.
1. You can submit as many times as needed.
1. You **must** give your submitted file the **identical** filename to that which you downloaded without changing **any** aspects - spaces, underscores, capitalisation etc. If your operating system has changed the filename because you downloaded the file twice or more you **must** also fix this.  



---

# <mark style="background: #843fa1; color: #ffffff;" >&nbsp;B4</mark>&nbsp;Topic 10: Working with Graphs 

In [3]:
import pandas as pd
import numpy as np
from numpy import nan

#### Question 01 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(5 Points)

Given the following undirected, unweighted graph:<br />
![unweighted undirected graph](https://zschub.github.io/img/unweighted-undirected.png)<br />
Write a function defined as:
```python
def edge_list():
```
that returns a list of edges where each edge is a set of two strings for the endpoint vertices of the edge. For example:
```python
def edge_list():
    return [{'0', '4'}, ...]
```
---
<details>
  <summary><span style="color:blue">What do I do?</span></summary>
   This is a manual task to record and return a set of edges from a graph image and serves as useful test data for following questions.
</details>

In [4]:
def edge_list():
    
    # YOUR CODE HERE
    graph = {'0': {'1', '3', '4'},
             '1': {'0', '2'},
             '2': {'1', '3'},
             '3': {'0', '2'},
             '4': {'0'}}
    
    edges = set()
    for vertix in graph.keys():
        for neighbor in graph[vertix]:
            vertix = int(vertix)
            neighbor = int(neighbor)
            edges.add((min(vertix, neighbor), max(vertix, neighbor)))
    
    edges = [{str(node) for node in edge} for edge in edges]
    return edges
elst = edge_list()
elst

[{'0', '1'}, {'1', '2'}, {'0', '4'}, {'0', '3'}, {'2', '3'}]

In [5]:
# Testing Cell (Do NOT modify this cell)

#### Question 02 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(5 Points)

Write a function defined as:
```python
def vertex_list(edge_list):
```
that examines a list of edges in the format used in Question 1 and extracts all of the vertices returning them in a set or `None` if the `edge_list` is empty. For example, the graph above (Qn 1) would return: 
```python
{'0', '1', '2', '3', '4'}
```

In [6]:
def vertex_list(edge_list):

    # YOUR CODE HERE
    result = {vertex for edge in edge_list for vertex in edge}
    return result if result else None

vlst = list(vertex_list(elst))

In [7]:
# Testing Cell (Do NOT modify this cell)

#### Question 03 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def adjacency_list_as_dict (vertex_list, edge_list):
```
that accepts a list of vertices and list of edges in the format defined in Question 1 (list of sets of adjacent vertices) and returns an adjacency list in the form of a dictionary where the key defines the vertex and the values contain a list of adjacent vertices.

For example, given the graph shown in Question 1, the function would return a dict as follows:
```python
{'0': ['4', '1', '3'],
 '1': ['0', '2'],
 '2': ['1', '3'],
 '3': ['2', '0'],
 '4': ['0']}
```

In [8]:
def adjacency_list_as_dict (vertex_list, edge_list):
    
    # YOUR CODE HERE
    result = {}
    for vertex in vertex_list:
        neighbour = list({vertices for edge in edge_list for vertices in edge if vertex in edge})
        neighbour.remove(vertex)
        result[vertex] = neighbour
    
    return result

adjacency_list_as_dict(vertex_list(elst), elst)

{'1': ['2', '0'],
 '2': ['1', '3'],
 '3': ['2', '0'],
 '4': ['0'],
 '0': ['1', '4', '3']}

In [9]:
# Testing Cell (Do NOT modify this cell)

#### Question 04 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(5 Points)

Given the following undirected, edge-weighted graph:<br />
![edge weighted undirected graph](https://zschub.github.io/img/undirected-edge-weighted.png)<br />
Write a function defined as:
```python
def edge_weighted_list():
```
that returns a list of edges where each edge is:
- a tuple containing two elements,
- firstly, a set of two strings for the endpoint vertices of the edge, and
- secondly, the weight of the edge.
For example:
```python
return [({'0', '4'}, 1), ...]
```
As for Question 1, this is a manual task of inspecting a graph and representing the edges and weights as a list and returning this from a function call.

In [10]:
def edge_weighted_list():

    # YOUR CODE HERE
    return [({'0', '4'}, 1), ({'0', '3'}, 5), ({'0', '1'}, 2), ({'1', '2'}, 2), ({'2', '3'}, 4)]

elst_1 = edge_weighted_list()
elst_1

[({'0', '4'}, 1),
 ({'0', '3'}, 5),
 ({'0', '1'}, 2),
 ({'1', '2'}, 2),
 ({'2', '3'}, 4)]

In [11]:
# Testing Cell (Do NOT modify this cell)

#### Question 05 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```Python
def adjacency_list_with_weights (vertex_list, edge_list):
```
that returns an adjacency list where:
- keys represent vertices,
- values represent a list of adjacent vertices,
- for each adjacent vertex, a two value tuple is provided with `(adjacent vertex, weight of edge)`.

For example, given the graph above, the function would return:
```python
{'0': [('4', 1), ('1', 2), ('3', 5)],
 '1': [('0', 2), ('2', 2)],
 '2': [('1', 2), ('3', 4)],
 '3': [('0', 5), ('2', 4)],
 '4': [('0', 1)]}
```
although key and values ordering may be different.

In [12]:
def adjacency_list_with_weights (vertex_list, edge_list):

    # YOUR CODE HERE
    result = {vertex: [] for vertex in vertex_list}
    
    for edge in edge_list:
        vertecies, weight = edge
        vertex1, vertex2 = vertecies
        result[vertex1].append((vertex2, weight))
        result[vertex2].append((vertex1, weight))
        
    return result

adjacency_list_with_weights(vlst, elst_1)

{'1': [('0', 2), ('2', 2)],
 '2': [('1', 2), ('3', 4)],
 '3': [('0', 5), ('2', 4)],
 '4': [('0', 1)],
 '0': [('4', 1), ('3', 5), ('1', 2)]}

In [13]:
# Testing Cell (Do NOT modify this cell)

#### Question 06 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

For a directed, unweighted graph such as this:<br />
![directed unweighted](https://zschub.github.io/img/directed-unweighted.jpg)<br />
Write a function defined as:
```python
def adjacency_list_directed (edge_list):
```
that accepts an adjacency list of a graph defined as list of directed edges in the form of tuples:
```python
[(origin, destination), ...]
```
and returns a dictionary whose keys are the vertex id's and whose values are a list of the adjacent verticies.
For example:
```python
{'0': ['1'], 
 '1': ['2'], 
 '2': ['3'], 
 '3': ['4', '0'], 
 '4': ['0']
}
```

In [14]:
def adjacency_list_directed (edge_list):
    
    # YOUR CODE HERE
    result = {}
    vertecies = {node for edge in edge_list for node in edge}
    for vertex in vertecies:
        result[vertex] = [edge[1] for edge in edge_list if edge[0] == vertex]
    
    return result

elst_6 = [('0', '1'), ('1', '2'), ('2', '3'), ('3', '0'), ('3', '4'), ('4', '0')]
adjacency_list_directed(elst_6)

{'1': ['2'], '2': ['3'], '3': ['0', '4'], '4': ['0'], '0': ['1']}

In [15]:
# Testing Cell (Do NOT modify this cell)

#### Question 07 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def adjacency_matrix_weighted_directed (edge_list):
```    
that accepts a list of weighted, directed edges in the form of tuples:
```python
(origin, destination, weight)
```
for a graph of the form:<br />
![directed unweighted](https://zschub.github.io/img/directed-weighted.jpg)<br />
and returns an Adjacency Matrix as a pandas `DataFrame` with the following features:
- diagonal (identity) values are represented with the weight '0',
- non traversable edges are represented by `NumPy.nan`,
- column and index values match the vertex labels and are in ascending order, and
- otherwise the matrix value represents the numeric weight of traversing the edge as a float value with index (row) as the origin and the column as the destination.

In [36]:
def adjacency_matrix_weighted_directed (edge_list):

    # YOUR CODE HERE
    vertecies = sorted({node for edge in edge_list for node in edge[:2]})
    vertex_mat = np.full((len(vertecies), len(vertecies)), np.nan)
    np.fill_diagonal(vertex_mat, 0)
    
    vertex_index = {vertex: i for i, vertex in enumerate(vertecies)}
    
    for origin, desitination, weight in edge_list:
        i, j = vertex_index[origin], vertex_index[desitination]
        vertex_mat[i][j] = float(weight)
    
    return pd.DataFrame(data=vertex_mat)

In [37]:
elst_7 = [('0', '1', 2), ('1', '2', 2), ('2', '3', 4), ('3', '0', 5), ('3', '4', 3), ('4', '0', 1)]
adjacency_matrix_weighted_directed(elst_7)

0    1    2    3    4
0  0.0  2.0  NaN  NaN  NaN
1  NaN  0.0  2.0  NaN  NaN
2  NaN  NaN  0.0  4.0  NaN
3  5.0  NaN  NaN  0.0  3.0
4  1.0  NaN  NaN  NaN  0.0

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 08 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def adjacency_matrix_unweighted_undirected (edge_list):
```
that returns a NumPy array with the adjacency matrix of a list of edges in the Question 1 format (a list of sets of adjacent vertices). 
- the axes of the array should reflect the sorted vertex values (so `'A', 'B', 'C'` rather than `'C', 'A', 'B'`.
- non adjacent vertices should be marked with 0,
- adjacent vertices should be marled with 1,
- looped vertices should be marked with 1, otherwise diagonal (identity) locations should be marked with 0.

Thus, a graph of the form:<br />
![directed unweighted](https://zschub.github.io/img/graph-basic.png)<br />should return:
```python
array([[0, 1, 0, 0, 1],
       [1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 1, 1, 1],
       [1, 0, 0, 1, 0]])
```

In [44]:
def adjacency_matrix_unweighted_undirected (edge_list):

    # YOUR CODE HERE
    vertecies = sorted({node for edge in edge_list for node in edge})
    matrix = np.zeros((len(vertecies), len(vertecies)), dtype=int)
    
    index = {vertex: i for i, vertex in enumerate(vertecies)}
    for edge in edge_list:
        node1, node2 = edge
        i, j = index[node1], index[node2]
        matrix[i, j] = matrix[j, i] = 1
        
    return matrix

In [52]:
elst_8 =  [{'A', 'B'}, {'B', 'C'}, {'C', 'D'}, {'A', 'E'}, {'B', 'D'},{'D', 'E'}, {'E', 'D'}]
adjacency_matrix_unweighted_undirected(elst_8)

array([[0, 1, 0, 0, 1],
       [1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 1, 0, 1],
       [1, 0, 0, 1, 0]])

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 09 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def degree_from_edges (edge_list, vertex):
```
that accepts a list of edges in the form of a list of sets (`[{'A', 'B'}, ...]`) and returns the degree of a vertex in the graph passed as a second parameter.

In [46]:
def degree_from_edges (edge_list, vertex):
    
    # YOUR CODE HERE
    return sum(1 for edge in edge_list if vertex in edge)

In [47]:
degree_from_edges(elst_8, 'A')

2

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 10 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def degrees_from_adjacency_matrix (adj_matrix):
```
that accepts a binary adjacency matrix formatted as per Question 8 (a NumPy array with adjacent vertices marked with 1 and otherwise 0) and returns a 1D `np.array` of integers being the degree of each vertex in the same sort order as the original indexing.

Thus, for the graph:<br /> ![unweighted undirected graph](https://zschub.github.io/img/unweighted-undirected.png)<br />
an input adjacency matrix:
```python
      [[0, 1, 0, 1, 1],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0],
       [1, 0, 0, 0, 0]]
```
would return:
```python
array([3, 2, 2, 2, 1])
```

In [48]:
def degrees_from_adjacency_matrix (adj_matrix):

    # YOUR CODE HERE
   return np.sum(adj_matrix, axis=0)

In [53]:
degrees_from_adjacency_matrix(adjacency_matrix_unweighted_undirected(elst_8))

array([2, 3, 2, 3, 2])

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 11 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def transform_list_to_matrix (adjacency_list):
```
that transforms an adjacency list for a directed graph (per Question 6 format: a dictionary where keys indicate vertex lables and values contain a list of adjacent (directed) vertices.

The function should construct a pandas `DataFrame` with the following features:
- diagonal (identity) values are represented with the value `0.0`,
- non traversable edges are represented by NumPy.nan,
- column and index values match the vertex labels, and
- traversable edges are indicated with the value `1.0` reading the directed adjacency matrix horizontally (the row shows the origin vertex and the column the destination).

Thus for the graph:<br />
![directed unweighted](https://zschub.github.io/img/directed-unweighted.jpg)<br />
represented by an adjacency list:
```python
{'0': ['1'], '1': ['2'], '2': ['3'], '3': ['4', '0'], '4': ['0']}
```
the `DataFrame` returned would have values:<br /><br />
![directed unweighted](https://zschub.github.io/img/adj-matrix.png)

In [83]:
def transform_list_to_matrix (adjacency_list: dict):

    # YOUR CODE HERE
    index = {vertex: i for i, vertex in enumerate(sorted(adjacency_list.keys()))}
    matrix = np.full((len(index), len(index)), np.nan)
    np.fill_diagonal(matrix, 0.0)
    
    for origin, destinations in adjacency_list.items():
        for destination in destinations:
            i, j = index[origin], index[destination]
            matrix[i, j] = 1.0
            
    return pd.DataFrame(data=matrix, index=sorted(adjacency_list.keys()), columns=sorted(adjacency_list.keys()))

In [ ]:
transform_list_to_matrix({'0': ['1'], '1': []})

TypeError: 'Series' object is not callable

In [ ]:
# Testing Cell (Do NOT modify this cell)