# Files

Given a list of files from the downloaded archive:

`['b2-1.txt', 'b2-2.txt', 'b2-3.txt', 'b2-4.txt']`  
that contain fragments of PEP 20 - The Zen of PythonLinks to an external site. such as:

`PEP 20 – The Zen of Python`  
`Beautiful is better than ugly.`  
`Explicit is better than implicit.`  
`Simple is better than complex.`  
`Complex is better than complicated.`  
create a new file 'zen-utf16.txt` that concatenates all of the contents of the files into one text file with the following requirements:

the first line of each file (a header line that reads "PEP 20 – The Zen of Python" is removed, and
the new file is saved with 'utf-16' encoding.
To test your work, you must read the file and print its contents. You must close all files after use - in particular the written file.

In [25]:
files = ['b2-1.txt', 'b2-2.txt', 'b2-3.txt', 'b2-4.txt']
lines_ = []
for file in files:
    with open (f'files/{file}','r' ,encoding='utf-8') as f:
        lines_.extend(f.readlines()[1:])
        
with open('files/zen-utf16.txt', 'w+', encoding='utf-16') as output:
    output.writelines(line for line in lines_)
    
with open('files/zen-utf16.txt', 'r', encoding='utf-16') as file:
    contents = file.readlines()
    for line in contents:
        print(line.strip())

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


# Structured Data

Given a list of dictionaries of the details of books by author Neal Stephenson like:

In [28]:

books = [
  {
    'title' : "The Big U",
    'author' : "Neal Stephenson",
    'publication-date' : "1984",
  },
  {
    'title' : "Snow Crash",
    'author' : "Neal Stephenson",
    'publication-date' : "1992",
    'awards' : "British Science Fiction Association Award, 1993",
  },
  {
    'title' : "Interface",
    'author' : "Neal Stephenson",
    'co-author' : "J. Frederick George",
    'publication-date' : "1994",
  },
  {
    'title' : "The Diamond Age: or A Young Lady's Illustrated Primer",
    'author' : "Neal Stephenson",
    'publication-date' : "1995",
    'awards' : "Hugo and Locus SF Awards winner, 1996; Nebula",
  },
  {
    'title' : "The Cobweb",
    'author' : "Neal Stephenson",
    'co-author' : "J. Frederick George",
    'publication-date' : "1996",
  },
]

write a function:
that saves the book details to a CSV file. Your file must include a header row based on the dictionary keys that you calculate based on the supplied dictionary (i.e. no hard coding the header!). You must print the contents of the saved file after it has been written to test your work.

In [29]:
import pandas as pd
def save_as_csv (booklist: dict, filename):
    '''
    Accepts a dictionry of book details and saves a csv
    file (including a header row based on the dictionary keys)
    to the filename provided.
    '''
    df = pd.DataFrame(booklist)
    df.to_csv(f'files/{filename}.csv', index=False)
    
save_as_csv(books, 'Neal')

# Numpy
Create a NumPy array using np.zeros() and amend it as follows:
$$
arr1 =
\begin{bmatrix}
    1 & 0 & 0 & 0 \\
    0 & 1 & 0 & 0 \\
    0 & 0 & 1 & 0 \\
    0 & 0 & 0 & 1
\end{bmatrix}
$$
Create a second NumPy array using the functions np.arange() and np.reshape():
$$
arr1 =
\begin{bmatrix}
    1 & 2 & 3 & 4 \\
    5 & 6 & 7 & 8 \\
    9 & 10 & 11 & 12 \\
    13 & 14 & 15 & 16
\end{bmatrix}
$$
Multiply arr1 by arr2 and assign the resultant matrix to variable arr3.

Copy arr3 to a new array arr4 leaving arr3 unchanged. Multiply each value of arr4 by a factor of 2. 

Print arr1, arr2, arr3 and arr4.

Your final arr4 should look like:
$$
arr4 = 
\begin{bmatrix}
    2 & 0 & 0 & 0 \\
    0 & 12 & 0 & 0 \\
    0 & 0 & 22 & 0 \\
    0 & 0 & 0 & 32
\end{bmatrix}
$$

In [12]:
import numpy as np
arr1 = np.zeros((4, 4), dtype=int)
arr1[0, 0] = arr1[1, 1] = arr1[2, 2] = arr1[3, 3] = 1

arr2 = np.arange(1, 17, 1).reshape(4,4)
arr3 = arr1 * arr2
arr4 = arr3 * 2
print(arr3, arr4)

[[ 1  0  0  0]
 [ 0  6  0  0]
 [ 0  0 11  0]
 [ 0  0  0 16]] [[ 2  0  0  0]
 [ 0 12  0  0]
 [ 0  0 22  0]
 [ 0  0  0 32]]


# Pandas
From the supplied files, readLinks to an external site. the CSV file full-book-list.csv into a DataFrame named df1. You may adopt any approach you wish to execute the following steps:  

create a copy of df1 that is called df2,  
drop the column 'author' from 'df2' in place,  
change the column headings in df2 to replace the dash separators ('-') with spaces and capitalize the column titles, as follows:  
        ` ['Title', 'Co author', 'Publication date', 'Awards', 'Sales']`  

set the index of df2 to the book 'Title' in place.  
Now create a DataFrame df3 that contains the 'Awards' received for each book which sold more than 100,000 copies leaving df2 unchanged.

In [23]:
import pandas as pd
df1 = pd.read_csv('files/full-book-list.csv')
df2 = df1.drop(columns=['author']).set_index('title')
df3 = df2[df2['sales'] > 100000]['awards']
df3

title
Snow Crash                                               British Science Fiction Association Award nomi...
The Diamond Age: or A Young Lady's Illustrated Primer    Hugo and Locus SF Awards winner, 1996; Nebula,...
Cryptonomicon                                            Locus SF Award winner, 2000; Hugo and Clarke A...
Name: awards, dtype: object

# Refactioring
Given the following function that identifies whether a list of numbers is monotonicLinks to an external site., apply at least three of the refactoring techniques outlined here to improve this code. For each applied technique, identify it numerically and include a brief comment to explain its use. For example:  


In [ ]:

# pattern 1, renamed parameter named 'a' to `input_list` to improve readability.

The three techniques selected must be unique (i.e.: you gain no credit for using the same technique three times).

In [24]:
def is_monotonic(a, st):
    """
    This function checks if a list of numbers is monotonic.

    Args:
        a (list): A list of numbers.
        st (bool): Flag to indicate strict or non-strict monotonicity.
                    If True, checks for strictly increasing/decreasing.
                    If False, checks for non-strict monotonicity.
                    Default is True.

    Returns:
        bool: True if the list is monotonic, False otherwise.

    """
    flag1 = True
    flag2 = True

    print (f'Checking {a} for strict monontone: {st == True}')

    i = 1
    
    while i < len(a):
        if st == False:
            if a[i] < a[i - 1]:
                flag1 = False
            elif a[i] > a[i - 1]:
                flag2 = False
            i = i + 1
    
        else:
            if a[i] <= a[i - 1]:
                flag1 = False
            elif a[i] >= a[i - 1]:
                flag2 = False 
            i = i + 1


    return flag1 or flag2

# Test cases

assert not is_monotonic ([6, 0, 1, 2, 2, 3], st = False)
assert is_monotonic ([-1, 0, 1, 2, 2, 3], st = False)
assert not is_monotonic ([-1, 0, 1, 2, 2, 3], st = True) 

Checking [6, 0, 1, 2, 2, 3] for strict monontone: False
Checking [-1, 0, 1, 2, 2, 3] for strict monontone: False
Checking [-1, 0, 1, 2, 2, 3] for strict monontone: True


In [29]:
def is_monotonic_refactor(target: list, strict: bool=True):
    if len(target) <= 1:
        return True
    if strict:
        is_decreased = all(target[i] > target[i + 1] for i in range(len(target) - 1))
        is_increased = all(target[i] < target[i + 1] for i in range(len(target) - 1))
    else:
        is_decreased = all(target[i] >= target[i + 1] for i in range(len(target) - 1))
        is_increased = all(target[i] <= target[i + 1] for i in range(len(target) - 1))
    return is_decreased or is_increased

In [2]:
def is_monotonic_recursive(target: list, strict: bool=True):

    
    def is_increased(target):
        if len(target) <= 1:
            return True
        if strict:
            if target[0] < target[1]:
                return is_increased(target[1:])
            return False
        else:
            if target[0] <= target[1]:
                return is_increased(target[1:])
            return False
        
    def is_decreased(target):
        if len(target) <= 1:
            return True
        if strict:
            if target[0] > target[1]:
                return is_decreased(target[1:])
            return False
        else:
            if target[0] >= target[1]:
                return is_decreased(target[1:])
            return False
    return is_decreased(target) or is_increased(target)

is_monotonic_recursive([1,2,3,4])


True

# Synthesis of Key Concepts
We wish to create a function to analyse a NumPy array of (somewhat) random numbers and save our analysis to a JSON file. The function has the following definition:

In [9]:
import json
import pandas as pd
import numpy as np
def summarise_and_save (filename, arr):
    '''
    Function that accepts a NumPy array of numeric data and calculates three
    characteristics:
       - the minimum value,
       - the maximum value, and
       - the mean value.
    The summary data and the array (rounded to two decimal places) are saved
    in JSON format to the supplied filename with keys: 'min', 'max', 'mean' and 'series'.   
    '''

Per the docstring, the function has the following requirements:

* accept a NumPy array,
* calculate min, max and mean values, 
* round all data to two decimal places, and
* save these values and the series to the filename in JSON format.

You are also given a function that repeatably generates a NumPy array of numbers according to a random seed to create test data:

In [3]:
import numpy as np

def generate_test_data (size, seed = 0, noise_amplitude = 2):

    np.random.seed(seed)

    arr = np.random.uniform(1, 100, size)
    arr.sort()

    # Fuzz the data a little
    noise = np.random.uniform(-noise_amplitude, noise_amplitude, size)
    arr += noise

    arr = np.clip(arr, 1, 100)

    return arr

Following a Red-Green-Refactor approach:

* create two failing test cases (functions) to test the incomplete function summarise_and_save,
* implement all of the requirements of the function as listed above, and
* retest your implementation to show transition from failing tests (red) to successful tests (green).  

Your test functions must handle all generated exceptions and return True if the test passed, otherwise False. After implementing the requirements listed and retesting, your output file should hold the following summary data (for seed = 0):

In [ ]:
{
    "min": 40.13,
    "max": 97.88,
    "mean": 62.15,
    "series": [
        40.13,
        43.06,
        44.59,
        56.65,
        53.62,
        59.02,
        63.02,
        73.13,
        90.40,
        97.88
    ]
}

In [18]:
def summarise_and_save (filename, arr):
    output = {}
    arr = np.round(arr, 2)
    output['min'] = np.min(arr)
    output['max'] = np.max(arr)
    output['mean'] = np.mean(arr)
    output['series'] = list(arr)
    with open(f'files/{filename}.json','w+') as file:
        json.dump(output, file)
    return output
summarise_and_save('arr1', generate_test_data(10))

{'min': np.float64(40.13),
 'max': np.float64(97.88),
 'mean': np.float64(62.15),
 'series': [np.float64(40.13),
  np.float64(43.06),
  np.float64(44.59),
  np.float64(56.65),
  np.float64(53.62),
  np.float64(59.02),
  np.float64(63.02),
  np.float64(73.13),
  np.float64(90.4),
  np.float64(97.88)]}

In [25]:
pd.read_json('files/arr1.json')

min    max   mean  series
0  40.13  97.88  62.15   40.13
1  40.13  97.88  62.15   43.06
2  40.13  97.88  62.15   44.59
3  40.13  97.88  62.15   56.65
4  40.13  97.88  62.15   53.62
5  40.13  97.88  62.15   59.02
6  40.13  97.88  62.15   63.02
7  40.13  97.88  62.15   73.13
8  40.13  97.88  62.15   90.40
9  40.13  97.88  62.15   97.88

In [26]:

def test(summarise_and_save):
    try:
        assert not summarise_and_save('arr1', generate_test_data(10))['max'] == 50, 'correct answer'
        assert not summarise_and_save('arr1', generate_test_data(10))['mean'] == 62.15232, 'correct answer'
        assert isinstance(pd.read_json('files/arr1.json')['series'][0], float), 'not a list'
        return True
        
    except AssertionError as e:
        print(f"tests didn't pass: {e}")
        return False
test(summarise_and_save)

True